# Font
font_family      Ubuntu Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

# Font Color
foreground #ffffff
cursor #f07427
selection_background #f07427
selection_foreground #000000

# Background
background #000000
background_opacity 0.5

# Layout
window_padding_width 8
