#preload = ~/.config/backgrounds/default.jpg
#wallpaper = , ~/.config/backgrounds/default.jpg

wallpaper {
  monitor = DP-1
  path = ~/.config/backgrounds/default.jpg
  fit_mode = cover
}

splash = false
