#preload = ~/.config/backgrounds/default.png
#wallpaper = , ~/.config/backgrounds/default.png

wallpaper {
  monitor = DP-1
  path = ~/.config/backgrounds/default.png
  fit_mode = cover
}

splash = false
